/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file prcm_am335x.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __prcm_am335x_H__
#define __prcm_am335x_H__

typedef struct prcm_am335x_reg{
	struct cm_per{
		uint32_t l4ls_clkstctrl;
		uint32_t l3s_clkstctrl;
		uint32_t l3_clkstctrl;
		uint32_t gpgmac0_clkctrl;
		uint32_t l4ls_clkctrl;
		uint32_t lcdc_clkctrl;
		uint32_t usb0_clkctrl;
		uint32_t tptc0_clkctrl;
		uint32_t emif_clkctrl;
		uint32_t l3_instr_clkctrl;
		uint32_t ocmcram_clkctrl;
		uint32_t gpmc_clkctrl;
		uint32_t timer2_clkctrl;
		uint32_t l3_clkctrl;
		uint32_t ocpwp_l3_clkstctrl;
	}per;
	struct cm_dpll{
		uint32_t clksel_timer2_clk;
	}dpll;
}prcm_am335x_reg_t;

typedef struct prcm_am335x_device{
	conf_object_t* obj;
	prcm_am335x_reg_t* regs;
}prcm_am335x_device;

#define CM_PER_L4LS_CLKSTCTRL   (0x0)
#define CM_PER_L3S_CLKSTCTRL   (0x4)
#define CM_PER_L4FW_CLKSTCTRL   (0x8)
#define CM_PER_L3_CLKSTCTRL   (0xc)
#define CM_PER_CPGMAC0_CLKCTRL   (0x14)
#define CM_PER_LCDC_CLKCTRL   (0x18)
#define CM_PER_USB0_CLKCTRL   (0x1c)
#define CM_PER_MLB_CLKCTRL   (0x20)
#define CM_PER_TPTC0_CLKCTRL   (0x24)
#define CM_PER_EMIF_CLKCTRL   (0x28)
#define CM_PER_OCMCRAM_CLKCTRL   (0x2c)
#define CM_PER_GPMC_CLKCTRL   (0x30)
#define CM_PER_MCASP0_CLKCTRL   (0x34)
#define CM_PER_UART5_CLKCTRL   (0x38)
#define CM_PER_MMC0_CLKCTRL   (0x3c)
#define CM_PER_ELM_CLKCTRL   (0x40)
#define CM_PER_I2C2_CLKCTRL   (0x44)
#define CM_PER_I2C1_CLKCTRL   (0x48)
#define CM_PER_SPI0_CLKCTRL   (0x4c)
#define CM_PER_SPI1_CLKCTRL   (0x50)
#define CM_PER_L4LS_CLKCTRL   (0x60)
#define CM_PER_L4FW_CLKCTRL   (0x64)
#define CM_PER_MCASP1_CLKCTRL   (0x68)
#define CM_PER_UART1_CLKCTRL   (0x6c)
#define CM_PER_UART2_CLKCTRL   (0x70)
#define CM_PER_UART3_CLKCTRL   (0x74)
#define CM_PER_UART4_CLKCTRL   (0x78)
#define CM_PER_TIMER7_CLKCTRL   (0x7c)
#define CM_PER_TIMER2_CLKCTRL   (0x80)
#define CM_PER_TIMER3_CLKCTRL   (0x84)
#define CM_PER_TIMER4_CLKCTRL   (0x88)
#define CM_PER_RNG_CLKCTRL   (0x90)
#define CM_PER_AES0_CLKCTRL   (0x94)
#define CM_PER_SHA0_CLKCTRL   (0xa0)
#define CM_PER_PKA_CLKCTRL   (0xa4)
#define CM_PER_GPIO6_CLKCTRL   (0xa8)
#define CM_PER_GPIO1_CLKCTRL   (0xac)
#define CM_PER_GPIO2_CLKCTRL   (0xb0)
#define CM_PER_GPIO3_CLKCTRL   (0xb4)
#define CM_PER_TPCC_CLKCTRL   (0xbc)
#define CM_PER_DCAN0_CLKCTRL   (0xc0)
#define CM_PER_DCAN1_CLKCTRL   (0xc4)
#define CM_PER_EPWMSS1_CLKCTRL   (0xcc)
#define CM_PER_EMIF_FW_CLKCTRL   (0xd0)
#define CM_PER_EPWMSS0_CLKCTRL   (0xd4)
#define CM_PER_EPWMSS2_CLKCTRL   (0xd8)
#define CM_PER_L3_INSTR_CLKCTRL   (0xdc)
#define CM_PER_L3_CLKCTRL   (0xe0)
#define CM_PER_IEEE5000_CLKCTRL   (0xe4)
#define CM_PER_ICSS_CLKCTRL   (0xe8)
#define CM_PER_TIMER5_CLKCTRL   (0xec)
#define CM_PER_TIMER6_CLKCTRL   (0xf0)
#define CM_PER_MMC1_CLKCTRL   (0xf4)
#define CM_PER_MMC2_CLKCTRL   (0xf8)
#define CM_PER_TPTC1_CLKCTRL   (0xfc)
#define CM_PER_TPTC2_CLKCTRL   (0x100)
#define CM_PER_SPINLOCK_CLKCTRL   (0x10c)
#define CM_PER_MAILBOX0_CLKCTRL   (0x110)
#define CM_PER_L4HS_CLKSTCTRL   (0x11c)
#define CM_PER_L4HS_CLKCTRL   (0x120)
#define CM_PER_MSTR_EXPS_CLKCTRL   (0x124)
#define CM_PER_SLV_EXPS_CLKCTRL   (0x128)
#define CM_PER_OCPWP_L3_CLKSTCTRL   (0x12c)
#define CM_PER_OCPWP_CLKCTRL   (0x130)
#define CM_PER_ICSS_CLKSTCTRL   (0x140)
#define CM_PER_CPSW_CLKSTCTRL   (0x144)
#define CM_PER_LCDC_CLKSTCTRL   (0x148)
#define CM_PER_CLKDIV32K_CLKCTRL   (0x14c)
#define CM_PER_CLK_24MHZ_CLKSTCTRL   (0x150)

#define SOC_CM_DPLL_REGS	(0x500)
#define CM_DPLL_CLKSEL_TIMER7_CLK   (SOC_CM_DPLL_REGS + 0x4)
#define CM_DPLL_CLKSEL_TIMER2_CLK   (SOC_CM_DPLL_REGS + 0x8)
#define CM_DPLL_CLKSEL_TIMER3_CLK   (SOC_CM_DPLL_REGS + 0xc)
#define CM_DPLL_CLKSEL_TIMER4_CLK   (SOC_CM_DPLL_REGS + 0x10)
#define CM_DPLL_CM_MAC_CLKSEL   (SOC_CM_DPLL_REGS + 0x14)
#define CM_DPLL_CLKSEL_TIMER5_CLK   (SOC_CM_DPLL_REGS + 0x18)
#define CM_DPLL_CLKSEL_TIMER6_CLK   (SOC_CM_DPLL_REGS + 0x1c)
#define CM_DPLL_CM_CPTS_RFT_CLKSEL   (SOC_CM_DPLL_REGS + 0x20)
#define CM_DPLL_CLKSEL_TIMER1MS_CLK   (SOC_CM_DPLL_REGS + 0x28)
#define CM_DPLL_CLKSEL_GFX_FCLK   (SOC_CM_DPLL_REGS + 0x2c)
#define CM_DPLL_CLKSEL_ICSS_OCP_CLK   (SOC_CM_DPLL_REGS + 0x30)
#define CM_DPLL_CLKSEL_LCDC_PIXEL_CLK   (SOC_CM_DPLL_REGS + 0x34)
#define CM_DPLL_CLKSEL_WDT1_CLK   (SOC_CM_DPLL_REGS + 0x38)
#define CM_DPLL_CLKSEL_GPIO0_DBCLK   (SOC_CM_DPLL_REGS + 0x3c)

#endif
