/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file timer_am335x.h
* @brief The definition of system controller 
* @author Kewei Yu: keweihk@gmail.com
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __timer_am335x_H__
#define __timer_am335x_H__

typedef struct timer_am335x_reg{
	uint32_t tidr;
	uint32_t tiocp_cfg;
	uint32_t irqstatus_raw;
	uint32_t irqstatus;
	uint32_t irqenable_set;
	uint32_t irqenable_clr;
	uint32_t irqwakeen;
	uint32_t tclr;
	uint32_t tcrr;
	uint32_t tldr;
	uint32_t ttgr;
	uint32_t twps;
	uint32_t tmar;
	uint32_t tcar1;
	uint32_t tsicr;
	uint32_t tcar2;
}timer_am335x_reg_t;

typedef struct timer_am335x_device{
	conf_object_t* obj;
	timer_am335x_reg_t* regs;
	general_signal_intf *signal;
}timer_am335x_device;

#define DMTIMER_TIDR		(0x0)
#define DMTIMER_TIOCP_CFG	(0x10)        
#define DMTIMER_IRQ_EOI		(0x20)
#define DMTIMER_IRQSTATUS_RAW	(0x24)
#define DMTIMER_IRQSTATUS	(0x28)
#define DMTIMER_IRQENABLE_SET	(0x2C)
#define DMTIMER_IRQENABLE_CLR	(0x30)
#define DMTIMER_IRQWAKEEN	(0x34)
#define DMTIMER_TCLR		(0x38)
#define DMTIMER_TCRR		(0x3C)
#define DMTIMER_TLDR		(0x40)
#define DMTIMER_TTGR		(0x44)
#define DMTIMER_TWPS		(0x48)
#define DMTIMER_TMAR		(0x4C)
#define DMTIMER_TCAR(n)		(0x50 + (((n) - 1) * 8))
#define DMTIMER_TSICR		(0x54)


/* TIDR */
#define DMTIMER_TIDR_CUSTOM   (0x000000C0u)
#define DMTIMER_TIDR_CUSTOM_SHIFT   (0x00000006u)
#define DMTIMER_TIDR_FUNC   (0x0FFF0000u)
#define DMTIMER_TIDR_FUNC_SHIFT   (0x00000010u)
#define DMTIMER_TIDR_R_RTL   (0x0000F800u)
#define DMTIMER_TIDR_R_RTL_SHIFT   (0x0000000Bu)
#define DMTIMER_TIDR_SCHEME   (0xC0000000u)
#define DMTIMER_TIDR_SCHEME_SHIFT   (0x0000001Eu)
#define DMTIMER_TIDR_SCHEME_HIGHLANDER0P8   (0x1u)
#define DMTIMER_TIDR_SCHEME_LEGACY   (0x0u)
#define DMTIMER_TIDR_X_MAJOR   (0x00000700u)
#define DMTIMER_TIDR_X_MAJOR_SHIFT   (0x00000008u)
#define DMTIMER_TIDR_Y_MINOR   (0x0000003Fu)
#define DMTIMER_TIDR_Y_MINOR_SHIFT   (0x00000000u)

/* TIOCP_CFG */
#define DMTIMER_TIOCP_CFG_SOFTRESET   (0x00000001u)
#define DMTIMER_TIOCP_CFG_SOFTRESET_SHIFT   (0x00000000u)
#define DMTIMER_TIOCP_CFG_SOFTRESET_DONE   (0x0u)
#define DMTIMER_TIOCP_CFG_SOFTRESET_INITIATE   (0x1u)
#define DMTIMER_TIOCP_CFG_SOFTRESET_ONGOING   (0x1u)

#define DMTIMER_TIOCP_CFG_EMUFREE   (0x00000002u)
#define DMTIMER_TIOCP_CFG_EMUFREE_SHIFT   (0x00000001u)
#define DMTIMER_TIOCP_CFG_EMUFREE_TIMER_FREE   (0x1u)
#define DMTIMER_TIOCP_CFG_EMUFREE_TIMER_FROZEN   (0x0u)

#define DMTIMER_TIOCP_CFG_IDLEMODE   (0x0000000Cu)
#define DMTIMER_TIOCP_CFG_IDLEMODE_SHIFT   (0x00000002u)
#define DMTIMER_TIOCP_CFG_IDLEMODE_FORCE   (0x0u)
#define DMTIMER_TIOCP_CFG_IDLEMODE_NOIDLE   (0x1u)
#define DMTIMER_TIOCP_CFG_IDLEMODE_SMART   (0x2u)
#define DMTIMER_TIOCP_CFG_IDLEMODE_WAKEUP   (0x3u)

/* TCLR */
#define DMTIMER_TCLR_AR   (0x00000002u)
#define DMTIMER_TCLR_AR_SHIFT   (0x00000001u)
#define DMTIMER_TCLR_AR_AUTO   (0x1u)
#define DMTIMER_TCLR_AR_ONESHOT   (0x0u)

#define DMTIMER_TCLR_CAPT_MODE   (0x00002000u)
#define DMTIMER_TCLR_CAPT_MODE_SHIFT   (0x0000000Du)
#define DMTIMER_TCLR_CAPT_MODE_SECOND   (0x1u)
#define DMTIMER_TCLR_CAPT_MODE_SINGLE   (0x0u)

#define DMTIMER_TCLR_CE   (0x00000040u)
#define DMTIMER_TCLR_CE_SHIFT   (0x00000006u)
#define DMTIMER_TCLR_CE_DISABLE   (0x0u)
#define DMTIMER_TCLR_CE_ENABLE   (0x1u)

#define DMTIMER_TCLR_GPO_CFG   (0x00004000u)
#define DMTIMER_TCLR_GPO_CFG_SHIFT   (0x0000000Eu)
#define DMTIMER_TCLR_GPO_CFG_DRIVE1   (0x1u)
#define DMTIMER_TCLR_GPO_CFG_DRIVE0   (0x0u)

#define DMTIMER_TCLR_PRE   (0x00000020u)
#define DMTIMER_TCLR_PRE_SHIFT   (0x00000005u)
#define DMTIMER_TCLR_PRE_DISABLE   (0x0u)
#define DMTIMER_TCLR_PRE_ENABLE   (0x1u)

#define DMTIMER_TCLR_PT   (0x00001000u)
#define DMTIMER_TCLR_PT_SHIFT   (0x0000000Cu)
#define DMTIMER_TCLR_PT_PULSE   (0x0u)
#define DMTIMER_TCLR_PT_TOGGLE   (0x1u)

#define DMTIMER_TCLR_PTV   (0x0000001Cu)
#define DMTIMER_TCLR_PTV_SHIFT   (0x00000002u)

#define DMTIMER_TCLR_SCPWM   (0x00000080u)
#define DMTIMER_TCLR_SCPWM_SHIFT   (0x00000007u)
#define DMTIMER_TCLR_SCPWM_CLEAR   (0x0u)
#define DMTIMER_TCLR_SCPWM_SET   (0x1u)

#define DMTIMER_TCLR_ST   (0x00000001u)
#define DMTIMER_TCLR_ST_SHIFT   (0x00000000u)
#define DMTIMER_TCLR_ST_START   (0x1u)
#define DMTIMER_TCLR_ST_STOP   (0x0u)

#define DMTIMER_TCLR_TCM   (0x00000300u)
#define DMTIMER_TCLR_TCM_SHIFT   (0x00000008u)
#define DMTIMER_TCLR_TCM_BOTH   (0x3u)
#define DMTIMER_TCLR_TCM_HIGHLOW   (0x2u)
#define DMTIMER_TCLR_TCM_LOWHIGH   (0x1u)
#define DMTIMER_TCLR_TCM_NOCAPTURE   (0x0u)

#define DMTIMER_TCLR_TRG   (0x00000C00u)
#define DMTIMER_TCLR_TRG_SHIFT   (0x0000000Au)
#define DMTIMER_TCLR_TRG_NOTRIGGER   (0x0u)
#define DMTIMER_TCLR_TRG_OVERFLOW   (0x1u)
#define DMTIMER_TCLR_TRG_OVERFLOWANDMATCH   (0x2u)

/* IRQSTATUS */
#define DMTIMER_IRQSTATUS_MAT_IT_FLAG   (0x00000001u)
#define DMTIMER_IRQSTATUS_MAT_IT_FLAG_SHIFT   (0x00000000u)
#define DMTIMER_IRQSTATUS_MAT_IT_FLAG_CLEAR   (0x1u)
#define DMTIMER_IRQSTATUS_MAT_IT_FLAG_NONE   (0x0u)
#define DMTIMER_IRQSTATUS_MAT_IT_FLAG_PENDING   (0x1u)

#define DMTIMER_IRQSTATUS_OVF_IT_FLAG   (0x00000002u)
#define DMTIMER_IRQSTATUS_OVF_IT_FLAG_SHIFT   (0x00000001u)
#define DMTIMER_IRQSTATUS_OVF_IT_FLAG_CLEAR   (0x1u)
#define DMTIMER_IRQSTATUS_OVF_IT_FLAG_NONE   (0x0u)
#define DMTIMER_IRQSTATUS_OVF_IT_FLAG_PENDING   (0x1u)

#define DMTIMER_IRQSTATUS_TCAR_IT_FLAG   (0x00000004u)
#define DMTIMER_IRQSTATUS_TCAR_IT_FLAG_SHIFT   (0x00000002u)
#define DMTIMER_IRQSTATUS_TCAR_IT_FLAG_CLEAR   (0x1u)
#define DMTIMER_IRQSTATUS_TCAR_IT_FLAG_NONE   (0x0u)
#define DMTIMER_IRQSTATUS_TCAR_IT_FLAG_PENDING   (0x1u)

/* IRQENABLE_CLR */
#define DMTIMER_IRQENABLE_CLR_MAT_EN_FLAG   (0x00000001u)
#define DMTIMER_IRQENABLE_CLR_MAT_EN_FLAG_SHIFT   (0x00000000u)
#define DMTIMER_IRQENABLE_CLR_MAT_EN_FLAG_DISABLE   (0x1u)
#define DMTIMER_IRQENABLE_CLR_MAT_EN_FLAG_DISABLED   (0x0u)
#define DMTIMER_IRQENABLE_CLR_MAT_EN_FLAG_ENABLED   (0x1u)

#define DMTIMER_IRQENABLE_CLR_OVF_EN_FLAG   (0x00000002u)
#define DMTIMER_IRQENABLE_CLR_OVF_EN_FLAG_SHIFT   (0x00000001u)
#define DMTIMER_IRQENABLE_CLR_OVF_EN_FLAG_DISABLE   (0x1u)
#define DMTIMER_IRQENABLE_CLR_OVF_EN_FLAG_DISABLED   (0x0u)
#define DMTIMER_IRQENABLE_CLR_OVF_EN_FLAG_ENABLED   (0x1u)
    
#define DMTIMER_IRQENABLE_CLR_TCAR_EN_FLAG   (0x00000004u)
#define DMTIMER_IRQENABLE_CLR_TCAR_EN_FLAG_SHIFT   (0x00000002u)
#define DMTIMER_IRQENABLE_CLR_TCAR_EN_FLAG_DISABLE   (0x1u)
#define DMTIMER_IRQENABLE_CLR_TCAR_EN_FLAG_DISABLED   (0x0u)
#define DMTIMER_IRQENABLE_CLR_TCAR_EN_FLAG_ENABLED   (0x1u)

#endif
