# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc
import os
import wx.grid

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class ConfigFile():
    file_name = 0
    mem_bank = 0
    rows = 10 
    cols = 4 
    fp = 0

skyeye_conf = ConfigFile()

class SetMemBank(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None)
 
        self.grid = wx.grid.Grid(self)

	colLabels = [" map ", " type ", " addr ", " size "]
        self.grid.CreateGrid(skyeye_conf.rows, skyeye_conf.cols)
	for row in range(4):
		self.grid.SetColLabelValue(row, colLabels[row])
 
        btn = wx.Button(self, label="Save")
        btn.Bind(wx.EVT_BUTTON, self.SaveConfig_button)
 
        self.Sizer = wx.BoxSizer(wx.VERTICAL)
        self.Sizer.Add(self.grid, 1, wx.EXPAND)
        self.Sizer.Add(btn, 0, wx.EXPAND)
 
    def SaveConfig_button(self, event):
	skyeye_conf.mem_bank = [[0 for col in range(skyeye_conf.cols)] for row in range(skyeye_conf.rows)]
	for row in range(skyeye_conf.rows):
		for col in range(skyeye_conf.cols):
			skyeye_conf.mem_bank[row][col] = self.grid.GetCellValue(row, col)
	self.Destroy()


class xrcmainframe(wx.Dialog):
#!XRCED:begin-block:xrcmainframe.PreCreate
    SetMemConfig = 0
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmainframe.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "mainframe")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_COMBOBOX, self.OnCombobox_arch_box, id=xrc.XRCID('arch_box'))
        self.Bind(wx.EVT_COMBOBOX, self.OnCombobox_cpu_box, id=xrc.XRCID('cpu_box'))
        self.Bind(wx.EVT_COMBOBOX, self.OnCombobox_mach_box, id=xrc.XRCID('mach_box'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_Set_Memory_Bank, id=xrc.XRCID('Set_Memory_Bank'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_load_file_path_button, id=xrc.XRCID('load_file_path_button'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_load_elf_path_button, id=xrc.XRCID('load_elf_path_button'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_reset_button, id=xrc.XRCID('reset_button'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_save_button, id=xrc.XRCID('save_button'))

#!XRCED:begin-block:xrcmainframe.OnCombobox_arch_box
    def OnCombobox_arch_box(self, evt):
        # Replace with event handler code
        print "OnCombobox_arch_box()"
#!XRCED:end-block:xrcmainframe.OnCombobox_arch_box        

#!XRCED:begin-block:xrcmainframe.OnCombobox_cpu_box
    def OnCombobox_cpu_box(self, evt):
        # Replace with event handler code
        print "OnCombobox_cpu_box()"
#!XRCED:end-block:xrcmainframe.OnCombobox_cpu_box        

#!XRCED:begin-block:xrcmainframe.OnCombobox_mach_box
    def OnCombobox_mach_box(self, evt):
        # Replace with event handler code
        print "OnCombobox_mach_box()"
#!XRCED:end-block:xrcmainframe.OnCombobox_mach_box        

#!XRCED:begin-block:xrcmainframe.OnButton_Set_Memory_Bank
    def OnButton_Set_Memory_Bank(self, evt):
        # Replace with event handler code
        print "OnButton_Set_Memory_Bank()"
	app = wx.PySimpleApp()
	self.SetMemConfig= SetMemBank()
	self.SetMemConfig.Show()
	app.MainLoop()
#!XRCED:end-block:xrcmainframe.OnButton_Set_Memory_Bank        

#!XRCED:begin-block:xrcmainframe.OnButton_load_file_path_button
    def OnButton_load_file_path_button(self, evt):
        # Replace with event handler code
        print "OnButton_load_file_path_button()"
	dialog = wx.FileDialog(None, "Choose a file",
        			os.getcwd(),"", "All files (*)|*", wx.OPEN)
	if dialog.ShowModal() == wx.ID_OK:
            self.FindWindowById(xrc.XRCID('load_file_path_val')).SetValue(dialog.GetPath())
	dialog.Destroy()
#!XRCED:end-block:xrcmainframe.OnButton_load_file_path_button        

#!XRCED:begin-block:xrcmainframe.OnButton_load_elf_path_button
    def OnButton_load_elf_path_button(self, evt):
        # Replace with event handler code
        print "OnButton_load_elf_path_button()"
	dialog = wx.FileDialog(None, "Choose a file",
        			os.getcwd(),"", "All files (*)|*", wx.OPEN)
	if dialog.ShowModal() == wx.ID_OK:
            self.FindWindowById(xrc.XRCID('load_elf_path')).SetValue(dialog.GetPath())
	dialog.Destroy()

#!XRCED:end-block:xrcmainframe.OnButton_load_elf_path_button        

#!XRCED:begin-block:xrcmainframe.OnButton_reset_button
    def OnButton_reset_button(self, evt):
        # Replace with event handler code
        print "OnButton_reset_button()"
#!XRCED:end-block:xrcmainframe.OnButton_reset_button        

#!XRCED:begin-block:xrcmainframe.OnButton_save_button
    def OnButton_save_button(self, evt):
        # Replace with event handler code
        print "OnButton_save_button()"
        dialog = wx.FileDialog(None, "Save skyeye.conf", os.getcwd(),"", "All files (*)|*", wx.SAVE)
        if dialog.ShowModal() == wx.ID_OK:
                configure_file =  dialog.GetPath()
                last_path = dialog.GetDirectory()

	skyeye_conf.file_name = configure_file
	fp = open(skyeye_conf.file_name, 'w+')

        arch_box = self.FindWindowById(xrc.XRCID('arch_box')).GetValue()
        fp.writelines('arch: ' + arch_box + '\n')

        cpu_box = self.FindWindowById(xrc.XRCID('cpu_box')).GetValue()
        fp.writelines('cpu: ' + cpu_box + '\n')

        mach_box = self.FindWindowById(xrc.XRCID('mach_box')).GetValue()
        fp.writelines('mach: ' + mach_box + '\n\n')

	fp.writelines('#address space\n')
	# set memory bank
        break_flag = False
        for row in range(skyeye_conf.rows):
            for col in range(skyeye_conf.cols):
                if skyeye_conf.mem_bank[row][col] == '':
                    break_flag = True
                    break
            if break_flag == True:
                break_flag = False
                continue
            fp.writelines('mem_bank: map=' + skyeye_conf.mem_bank[row][0] +
		', type=' +  skyeye_conf.mem_bank[row][1] +
		', addr=' + skyeye_conf.mem_bank[row][2] +
		', size=' + skyeye_conf.mem_bank[row][3] + '\n')
        fp.writelines('\n')

	fp.writelines('uart:mod=term\n\n')

	#Fill the load_file option
	load_file_path_val = self.FindWindowById(xrc.XRCID('load_file_path_val')).GetValue()
        addr_text_val = self.FindWindowById(xrc.XRCID('addr_text_val')).GetValue()
	if(load_file_path_val != ''):
		fp.writelines('load_file: filename=' + load_file_path_val +
				', start=' + addr_text_val + '\n')

	load_elf_path = self.FindWindowById(xrc.XRCID('load_elf_path')).GetValue()
	if(load_elf_path!= ''):
		fp.writelines('load_elf: filename=' + load_elf_path + '\n')

	fp.close()
#!XRCED:end-block:xrcmainframe.OnButton_save_button        



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    set_configure_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="mainframe">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxStaticText" name="dec_text">
              <label>The option of skyeye</label>
            </object>
            <flag>wxALL|wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>0,10</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="sizeritem">
                <object class="wxFlexGridSizer">
                  <object class="sizeritem">
                    <object class="wxStaticText" name="arch_text">
                      <label>arch:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <orient>wxHORIZONTAL</orient>
                      <object class="sizeritem">
                        <object class="wxComboBox" name="arch_box">
                          <content>
                            <item>arm</item>
                            <item>powerpc</item>
                            <item>x86</item>
                            <item>mips</item>
                          </content>
                          <value>arm</value>
                          <style>wxCB_READONLY</style>
                          <XRCED>
                            <events>EVT_COMBOBOX</events>
                          </XRCED>
                        </object>
                      </object>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="cpu_text">
                      <label>cpu:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <orient>wxHORIZONTAL</orient>
                      <object class="sizeritem">
                        <object class="wxComboBox" name="cpu_box">
                          <content>
                            <item>arm710</item>
                            <item>arm7tdmi</item>
                            <item>arm720t</item>
                            <item>sa1110</item>
                            <item>sa1100</item>
                            <item>arm920t</item>
                            <item>arm926ejs</item>
                            <item>pxa25x</item>
                            <item>pxa27x</item>
                            <item>arm11</item>
                          </content>
                          <value>arm920t</value>
                          <style>wxCB_READONLY</style>
                          <XRCED>
                            <events>EVT_COMBOBOX</events>
                          </XRCED>
                        </object>
                      </object>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="mach_text">
                      <label>mach:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <object class="sizeritem">
                        <object class="wxComboBox" name="mach_box">
                          <content>
                            <item>at91rm92</item>
                            <item>pxa_lubbock</item>
                            <item>pxa_mainstone</item>
                            <item>s3c2410x</item>
                            <item>s3c2440</item>
                            <item>s3c6410</item>
                          </content>
                          <value>s3c2410x</value>
                          <style>wxCB_READONLY</style>
                          <XRCED>
                            <events>EVT_COMBOBOX</events>
                          </XRCED>
                        </object>
                        <option>1</option>
                      </object>
                      <orient>wxHORIZONTAL</orient>
                    </object>
                    <option>1</option>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="mem_bank_text">
                      <label>mem_bank:</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <orient>wxVERTICAL</orient>
                      <object class="sizeritem">
                        <object class="wxButton" name="Set_Memory_Bank">
                          <label>Set Memory Bank</label>
                          <default>1</default>
                          <XRCED>
                            <events>EVT_BUTTON</events>
                          </XRCED>
                        </object>
                      </object>
                    </object>
                    <flag>wxALL|wxEXPAND|wxADJUST_MINSIZE</flag>
                    <minsize>150</minsize>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="load_file_text">
                      <label>load_file:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxFlexGridSizer">
                      <object class="sizeritem">
                        <object class="wxBoxSizer">
                          <orient>wxHORIZONTAL</orient>
                          <object class="spacer">
                            <size>45,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxStaticText" name="load_file_path_text">
                              <label>path:</label>
                            </object>
                            <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                          </object>
                          <object class="sizeritem">
                            <object class="wxTextCtrl" name="load_file_path_val"/>
                            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
                            <minsize>210, -1</minsize>
                          </object>
                          <object class="spacer">
                            <size>5,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxButton" name="load_file_path_button">
                              <label>Browse...</label>
                              <XRCED>
                                <events>EVT_BUTTON</events>
                              </XRCED>
                            </object>
                          </object>
                        </object>
                        <option>1</option>
                      </object>
                      <object class="spacer">
                        <size>20,0</size>
                      </object>
                      <object class="sizeritem">
                        <object class="wxBoxSizer">
                          <orient>wxHORIZONTAL</orient>
                          <object class="sizeritem">
                            <object class="wxStaticText" name="addr_text">
                              <label>initrd_start:</label>
                            </object>
                            <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                          </object>
                          <object class="sizeritem">
                            <object class="wxTextCtrl" name="addr_text_val"/>
                            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
                            <minsize>210, -1</minsize>
                          </object>
                        </object>
                        <option>1</option>
                      </object>
                      <cols>2</cols>
                      <rows>2</rows>
                    </object>
                  </object>
                  <cols>2</cols>
                  <vgap>5</vgap>
                  <hgap>20</hgap>
                  <growablecols>1</growablecols>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="load_elf_text">
                      <label>load_elf:</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxFlexGridSizer">
                      <object class="sizeritem">
                        <object class="wxBoxSizer">
                          <orient>wxHORIZONTAL</orient>
                          <object class="spacer">
                            <size>7,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxStaticText" name="file_name">
                              <label>file_name:</label>
                            </object>
                            <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                          </object>
                          <object class="sizeritem">
                            <object class="wxTextCtrl" name="load_elf_path"/>
                            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
                            <minsize>210, -1</minsize>
                          </object>
                          <object class="spacer">
                            <size>5,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxButton" name="load_elf_path_button">
                              <label>Browse...</label>
                              <XRCED>
                                <events>EVT_BUTTON</events>
                              </XRCED>
                            </object>
                          </object>
                        </object>
                        <option>1</option>
                      </object>
                      <object class="spacer">
                        <size>20,0</size>
                      </object>
                      <cols>2</cols>
                      <rows>2</rows>
                    </object>
                  </object>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
              </object>
              <label>Options:</label>
              <orient>wxVERTICAL</orient>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <minsize>1000,800</minsize>
          </object>
          <object class="spacer">
            <size>0,10</size>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <orient>wxHORIZONTAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>3</cols>
                  <object class="spacer"/>
                  <object class="sizeritem">
                    <object class="wxButton" name="reset_button">
                      <label>reset</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxEXPAND</flag>
                  </object>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxButton" name="save_button">
                      <label>save</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxEXPAND</flag>
                  </object>
                </object>
              </object>
            </object>
            <flag>wxALIGN_RIGHT</flag>
          </object>
          <orient>wxVERTICAL</orient>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
      </object>
    </object>
    <title>skyeye.conf</title>
    <font>
      <size>11</size>
      <style>normal</style>
      <weight>normal</weight>
      <underlined>0</underlined>
      <family>default</family>
      <face>Ubuntu</face>
      <encoding>UTF-8</encoding>
    </font>
    <style>wxCAPTION|wxRESIZE_BORDER|wxRESIZE_BOX|wxCLOSE_BOX|wxMAXIMIZE_BOX</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/set_configure/set_configure_xrc', set_configure_xrc)
    __res.Load('memory:XRC/set_configure/set_configure_xrc')

