/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file emif_6713.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __emif_6713_H__
#define __emif_6713_H__

typedef struct emif_6713_reg{
	uint32_t gbl_ctl;
	uint32_t ce_ctl[4];
	uint32_t sd_ctl;
	uint32_t sd_tim;
	uint32_t sd_ext;
}emif_6713_reg_t;

typedef struct emif_6713_device{
	conf_object_t* obj;
	emif_6713_reg_t* regs;
}emif_6713_device;

#endif
