/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file can_sja1000.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __can_sja1000_H__
#define __can_sja1000_H__

typedef struct can_sja1000_reg{
	uint8_t mode;
	uint8_t ier;
	uint8_t output_ctrl;
	uint8_t error_code;
	
}can_sja1000_reg_t;

typedef struct can_sja1000_device{
	conf_object_t* obj;
	can_sja1000_reg_t* regs;
	can_ops_intf* can_ops;
}can_sja1000_device;

#endif
