/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file intc_xdht.h
* @brief The definition of system controller 
* @author ZYUMING: zyumingfit@gmail.com
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __intc_xdht_H__
#define __intc_xdht_H__

#define BP2007ADD    (unsigned short *)0x1000000
#define INT_ADD_OFFSET 8
#define DUMP_BASE 8
#define REG_IFR0_ADD (BP2007ADD + 0x3100)    // IFR_63  0x313f  R     ADDR 0x1006200
#define REG_IFCR0_ADD (BP2007ADD + 0x3140)   // IFCR_63 0x317f  W     ADDR 0x1006280
#define REG_IER0_ADD (BP2007ADD + 0x3180)    //                 R/W   ADDR 0x1006360


#define REG_INT_BASE (BP2007ADD + 0x3100)
#define REG_IFR0_BASE (BP2007ADD + 0x3100)
#define REG_IFCR0_BASE (BP2007ADD + 0x3140)
#define REG_IER0_BASE (BP2007ADD + 0x3180)
#define REG_ADDR  ((unsigned short *)(0x1006200 + offset))


#define REG_SIZE 16
//INTERFACE OFFSET
#define INTERFACEINT_UART		0x00	//UART中断状态/清除寄存器偏移（bitn对应n通道）
#define INTERFACEINT_CAN		0x01	//CAN中断状态/清除寄存器偏移（bitn对应n通道）
#define INTERFACEINT_OTHER		0x02	//OTHERS中断状态/清除寄存器偏移（bitn对应n通道）



typedef struct INTCSTATE{
	conf_object_t* obj;
	struct registers{
		uint16 ifr[64];
		uint16 ifcr[64];
		uint16 ier;
	}regs;
	general_signal_intf *signal;
}xdht_intc_dev;

/*
 * Registers Definition
 */



#endif
